# Generated by Django 5.1.3 on 2025-01-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'verbose_name_plural': 'Buy'},
        ),
    ]
