# Generated by Django 5.1.3 on 2025-01-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
