# Generated by Django 5.1.3 on 2025-01-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mango',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
