# Generated by Django 5.1.3 on 2025-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_mango_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mango',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
