# Generated by Django 5.1.3 on 2025-01-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0002_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_to_cart.addtocart'),
        ),
    ]
