# Generated by Django 5.1.3 on 2025-01-02 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0003_buy_cart_item'),
        ('product', '0004_mango_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='Order',
        ),
    ]
