# Generated by Django 5.1.3 on 2025-01-02 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0006_remove_orderusingcart_product'),
        ('product', '0004_mango_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDirectly',
            new_name='Order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.DeleteModel(
            name='OrderUsingCart',
        ),
    ]
