# Generated by Django 5.1.3 on 2025-01-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_to_cart.cart'),
        ),
    ]
