# Generated by Django 5.1.3 on 2025-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0010_addtocart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
